Feature/heists graphql
YummYume/symmetrical-potato pull request #73
Opened 2023-11-19 18:30 UTC by Spacelocust

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

#50 

## Type of change

Please add any relevant information to the type of change you've made.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update (or is a documentation update)
-   [x] HIGH IMPORTANCE (requires a fast merging)

## Has This Been Tested?

Please describe the tests that you ran to verify your changes. It is way more likely for a PR to be merged and approved with successful tests.

-   [x] Yes, I ran tests
-   [ ] No, I did not include any test
-   [ ] No test is needed for this change

2023-11-20 22:58 UTC, YummYume requested changes

2023-11-20 22:58 UTC, YummYume commented on api/migrations/Version20231116130737.php
> +        return '';
Ajouter une description

2023-11-20 22:58 UTC, YummYume commented on api/migrations/Version20231119174434.php
> +        return '';
Ajouter une description

2023-11-20 22:58 UTC, YummYume commented on api/src/Doctrine/GetHeistExtension.php
> +class GetHeistExtension implements QueryCollectionExtensionInterface, QueryItemExtensionInterface
```suggestion
final class GetHeistExtension implements QueryCollectionExtensionInterface, QueryItemExtensionInterface
```

2023-11-20 22:58 UTC, YummYume commented on api/src/Doctrine/GetHeistExtension.php
> +     * @param array<string> $context
```suggestion
     * @param array<string, mixed> $context
```

2023-11-20 22:58 UTC, YummYume commented on api/src/Doctrine/GetHeistExtension.php
> +     * @param array<string> $context
```suggestion
     * @param array<string, mixed> $context
```

2023-11-20 22:58 UTC, YummYume commented on api/src/Doctrine/GetHeistExtension.php
> +        $user = $this->security->getUser();
```suggestion
        $user = $this->security->getUser();

        if (Heist::class !== $resourceClass || !$user instanceof User::class) {
            return;
        }
```

2023-11-20 22:58 UTC, YummYume commented on api/src/Doctrine/GetHeistExtension.php
> +        if (null === $user || !array_intersect($user->getRoles(), [User::ROLE_ADMIN, User::ROLE_CONTRACTOR])) {
```suggestion
        if (null === $user || !array_intersect($user->getRoles(), [User::ROLE_ADMIN, User::ROLE_CONTRACTOR])) {
```

Il faut utiliser `$this->security->isGranted`

2023-11-20 22:58 UTC, YummYume commented on api/src/Entity/Heist.php
> +        $this->isFinished = (bool) $endedAt;
```suggestion
```

2023-11-20 22:58 UTC, YummYume commented on api/src/Entity/Heist.php
> +    private bool $isFinished = false;
```suggestion
```

2023-11-20 22:58 UTC, YummYume commented on api/src/Entity/Heist.php
> +    }
```suggestion
    #[ApiProperty]
    #[Groups(['heist:read'])]
    public function isFinished(): bool
    {
        return HeistPhaseEnum::isFinished($this->phase);
    }
```

2023-11-20 22:58 UTC, YummYume commented on api/src/Entity/User.php
> +                'groups' => ['user:read'],
Attention `user:read` c'est pour l'utilisateur concerné, `user:read:public` c'est pour la vue publique

2023-11-20 22:58 UTC, YummYume commented on api/src/Filter/UuidFilter.php
> +            $value = Uuid::fromString($this->getIdFromURI($value))->toBinary();
Sinon faire une recherche avec l'UUID directement sans le binaire ? Je ne sais pas ce qui est le mieux

2023-11-20 22:58 UTC, YummYume commented on api/src/Helper/StringFormatHelper.php
> +final class StringFormatHelper
Utiliser https://symfony.com/doc/current/components/string.html plutôt ?

2023-11-20 22:58 UTC, YummYume commented on api/tests/AbstractTestCase.php
> +    protected static function getHas(string $grapqlQuery, array $result, string $username = null): void
C'est très bizarre et pas explicite comme nom de fonction, normalement c'est soit un getter (`get[...]`) ou un hasser (`has[...]`)

2023-11-20 22:58 UTC, YummYume commented on api/tests/AbstractTestCase.php
> +        }
```suggestion
    protected static function createAuthenticatedClient(string $username = 'dallas', string $password = 'xxx'): array
    {
```

2023-11-20 22:58 UTC, YummYume commented on api/tests/API/HeistTest.php
> +        [$client, $userId] = static::createAuthenticatedClient(self::EMPLOYEE);
S'il faut mettre le type à chaque fois ici, c'est que la fonction est mal typée

2023-11-20 22:58 UTC, YummYume commented on api/tests/API/HeistTest.php
> +    public function testGetHeistsLinkedToAEmployee(): void
```suggestion
    public function testGetHeistsLinkedToAnEmployee(): void
```

2023-11-20 22:58 UTC, YummYume commented on api/src/Entity/Heist.php
>  class Heist
Il faut ajouter la sécurité (être connecté). À voir aussi s'il ne faut pas plutôt mettre un groupe comme `heist:read:public` si jamais le contracteur doit avoir une vue différente

2023-11-21 09:32 UTC, Spacelocust commented on api/src/Entity/Heist.php
> +    }
J'avais fait ça au début, le problème, c'est que les filtres ne fonctionnent pas avec les propriétés non mappées par Doctrine

2023-11-21 09:36 UTC, Spacelocust commented on api/src/Filter/UuidFilter.php
> +            $value = Uuid::fromString($this->getIdFromURI($value))->toBinary();
Le problème, c'est que l'on est obligé de passer par un binaire, soit en le convertissant comme ça, ou par le biais du type dans le query builder

2023-11-21 10:34 UTC, Spacelocust commented on api/src/Entity/Heist.php
>  class Heist
Je rajoute le groupe au cas où, pour l'instant, je ne vois pas de données qui être affichés ou non en fonction du rôle

2023-11-21 23:10 UTC, YummYume commented on api/migrations/Version20231119174434.php
> +<?php
Delete

2023-11-21 23:10 UTC, YummYume commented on api/src/Filter/MatchFilter.php
> +        // $constrains = explode('|', $value);
```suggestion
```

2023-11-21 23:10 UTC, YummYume commented on api/tests/API/HeistTest.php
> +     * @description This method is used to test if a employee can get all the finished heists he is related to
```suggestion
     * This method is used to test if an employee can get all the finished heists they are related to
```

2023-11-21 23:10 UTC, YummYume commented on api/tests/API/HeistTest.php
> +     * @description This method is used to test if a employee can get all the finished heists he is related to
Pareil pour les autres

2023-11-21 23:10 UTC, YummYume commented on api/tests/AbstractTestCase.php
> +     * This method check depending on the user if the resource is the same as the expected result.
```suggestion
     * This method checks if the resource is the same as the expected result. Can be given a user to authenticate.
```

2023-11-22 14:57 UTC, YummYume approved these changes

2023-11-22 14:57 UTC, merged